const AIRLINE_NAMES: Record<string, string> = {
  "2B": "Albawings",
  "3K": "Jetstar Asia",
  "3U": "Sichuan Airlines",
  "4U": "Germanwings",
  "5J": "Cebu Pacific",
  "5X": "UPS Airlines",
  "6E": "IndiGo",
  "7C": "Jeju Air",
  "9W": "Jet Airways",
  AA: "American Airlines",
  AB: "Air Berlin",
  AC: "Air Canada",
  AF: "Air France",
  AI: "Air India",
  AK: "AirAsia",
  AM: "Aeroméxico",
  AY: "Finnair",
  AZ: "ITA Airways",
  B6: "JetBlue",
  BA: "British Airways",
  BG: "Biman Bangladesh",
  BI: "Royal Brunei",
  BJ: "Nouvelair",
  BR: "EVA Air",
  BT: "airBaltic",
  CA: "Air China",
  CI: "China Airlines",
  CM: "Copa Airlines",
  CX: "Cathay Pacific",
  CZ: "China Southern",
  D8: "Norwegian",
  DE: "Condor",
  DL: "Delta Air Lines",
  EI: "Aer Lingus",
  EK: "Emirates",
  ET: "Ethiopian Airlines",
  EY: "Etihad Airways",
  FB: "Bulgaria Air",
  FI: "Icelandair",
  FJ: "Fiji Airways",
  FR: "Ryanair",
  FZ: "flydubai",
  G3: "Gol",
  G9: "Air Arabia",
  GF: "Gulf Air",
  HA: "Hawaiian Airlines",
  HO: "Juneyao Airlines",
  HU: "Hainan Airlines",
  HX: "Hong Kong Airlines",
  IB: "Iberia",
  ID: "Batik Air",
  IT: "Tigerair Taiwan",
  JL: "Japan Airlines",
  JP: "Adria Airways",
  JQ: "Jetstar",
  KA: "Cathay Dragon",
  KC: "Air Astana",
  KE: "Korean Air",
  KL: "KLM",
  KQ: "Kenya Airways",
  LA: "LATAM Airlines",
  LH: "Lufthansa",
  LO: "LOT Polish Airlines",
  LX: "Swiss",
  LY: "El Al",
  MF: "Xiamen Airlines",
  MH: "Malaysia Airlines",
  MI: "SilkAir",
  MK: "Air Mauritius",
  MS: "EgyptAir",
  MU: "China Eastern",
  NH: "All Nippon Airways",
  NZ: "Air New Zealand",
  OK: "Czech Airlines",
  OM: "MIAT Mongolian Airlines",
  OS: "Austrian Airlines",
  OZ: "Asiana Airlines",
  PC: "Pegasus Airlines",
  PR: "Philippine Airlines",
  PS: "Ukraine International",
  PX: "Air Niugini",
  QF: "Qantas",
  QR: "Qatar Airways",
  RJ: "Royal Jordanian",
  RO: "TAROM",
  S7: "S7 Airlines",
  SA: "South African Airways",
  SC: "Shandong Airlines",
  SK: "SAS",
  SN: "Brussels Airlines",
  SQ: "Singapore Airlines",
  SU: "Aeroflot",
  TG: "Thai Airways",
  TK: "Turkish Airlines",
  TN: "Air Tahiti Nui",
  TP: "TAP Air Portugal",
  TR: "Scoot",
  TW: "T'way Air",
  UA: "United Airlines",
  UL: "SriLankan Airlines",
  UM: "Air Zimbabwe",
  UO: "Hong Kong Express",
  UX: "Air Europa",
  VJ: "VietJet Air",
  VN: "Vietnam Airlines",
  VF: "Ajet",
  VS: "Virgin Atlantic",
  VY: "Vueling",
  W6: "Wizz Air",
  WN: "Southwest Airlines",
  WS: "WestJet",
  WY: "Oman Air",
  XJ: "Thai AirAsia X",
  XQ: "SunExpress",
  Z2: "Philippines AirAsia",
  ZH: "Shenzhen Airlines",
};

export function airlineName(code: string): string {
  return AIRLINE_NAMES[code.toUpperCase()] ?? code;
}

export function airlineNames(codes: string[]): string {
  return codes.map(airlineName).join(", ");
}
