#!/usr/bin/env bash
# Pre-deployment validation: type check, bundle inspection, data integrity.
# Usage: bash scripts/validate.sh [--full]
# --full: also checks deployed GitHub Pages (requires network)
#
# REGRESSION-PROOFING (viz CLAUDE.md "Poučení z chyb"): každý nově objevený typ
# chyby, který lze detekovat skriptem, sem přidej jako novou kontrolu s exit 1.
# Kontroly nikdy neodstraňuj — chrání před opakováním už vyřešených chyb.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

echo "=========================================="
echo "VALIDATION SUITE — Flight Watcher"
echo "=========================================="

# 1. TypeScript — no type errors
echo ""
echo "[1/7] TypeScript type check..."
cd web
if npx tsc --noEmit 2>&1 | grep -q "error TS"; then
  echo "❌ Type errors found. Run: npm run build"
  exit 1
fi
echo "✓ No type errors"

# 2. Build artifact exists and is valid
echo ""
echo "[2/7] Build artifacts..."
if [ ! -d "dist/assets" ] || [ ! -f "dist/index.html" ]; then
  echo "❌ dist/ not found. Run: npm run build"
  exit 1
fi
echo "✓ dist/ exists"

# 3. Check index.html references valid asset hashes
echo ""
echo "[3/7] index.html asset references..."
JS_REF=$(grep -o 'assets/index-[^"]*\.js' dist/index.html || echo "")
CSS_REF=$(grep -o 'assets/index-[^"]*\.css' dist/index.html || echo "")
if [ -z "$JS_REF" ] || [ -z "$CSS_REF" ]; then
  echo "❌ index.html missing asset references"
  exit 1
fi
if [ ! -f "dist/$JS_REF" ] || [ ! -f "dist/$CSS_REF" ]; then
  echo "❌ Referenced assets do not exist: $JS_REF or $CSS_REF"
  exit 1
fi
echo "✓ index.html references valid assets: $(basename $JS_REF), $(basename $CSS_REF)"

# 4. Bundle contains implementation code (UI strings from components)
echo ""
echo "[4/7] Bundle implementation check..."
CHECKS=(
  "Kalendář dostupných:calendar heatmap"
  "Načítám historii:route detail view"
  "Aktuální nejlepší nabídky:offers table"
  "nejnižší nalezená cena:summary stats"
  "Uložit konfiguraci na GitHub:settings page"
)
FAILED=0
for check in "${CHECKS[@]}"; do
  PATTERN="${check%:*}"
  DESC="${check#*:}"
  if ! grep -q "$PATTERN" "dist/$JS_REF"; then
    echo "  ❌ Missing: $DESC"
    FAILED=1
  else
    echo "  ✓ $DESC"
  fi
done
if [ $FAILED -eq 1 ]; then exit 1; fi

# 4b. Google Flights "Prostředek" (mode=let) deep-link must use the tfs protobuf
#     param — the natural-language q= param does NOT fill the destination
#     (regression: cíl "Kam?" zůstal prázdný u dotazu s více odletovými letišti).
if ! grep -q "travel/flights?tfs=" "dist/$JS_REF"; then
  echo "  ❌ Missing: Google Flights tfs deep-link (mode=let)"
  exit 1
fi
if grep -q "q=flights+MUC,NUE" "dist/$JS_REF"; then
  echo "  ❌ Broken Google Flights q= link present (musí být tfs=, ne q=flights+...)"
  exit 1
fi
echo "  ✓ Google Flights tfs deep-link"

# 5. Data files exist and are valid JSON (checked only if they're loaded)
echo ""
echo "[5/7] Data files integrity..."
DATAFILES=(
  "public/data/latest.json"
  "public/data/stats.json"
  "public/config/agent.json"
)
for file in "${DATAFILES[@]}"; do
  if [ ! -f "$file" ]; then
    echo "  ❌ Missing: $file"
    exit 1
  fi
  if ! jq empty "$file" 2>/dev/null; then
    echo "  ❌ Invalid JSON: $file"
    exit 1
  fi
  echo "  ✓ $(basename $file)"
done

# routes.json, meta.json, insights.json are generated by scanner and optional in dev
OPTIONAL_FILES=(
  "public/data/routes.json"
  "public/data/meta.json"
  "public/data/insights.json"
)
for file in "${OPTIONAL_FILES[@]}"; do
  if [ -f "$file" ]; then
    if jq empty "$file" 2>/dev/null; then
      echo "  ✓ $(basename $file)"
    else
      echo "  ❌ Invalid JSON: $file"
      exit 1
    fi
  fi
done

# 5b. One-way pollution guard (sdílený se scripts/validate-data.sh — jeden zdroj
#     pravdy). Stejná kontrola běží i v CI scan jobu PŘED commitem exportu, aby
#     se znečištěná data nikdy nedostala na main. Detaily viz validate-data.sh.
echo ""
echo "[5b] One-way pollution guard..."
bash "$REPO_ROOT/scripts/validate-data.sh" "$REPO_ROOT/web/public/data" >/dev/null
echo "  ✓ Žádná roundtrip/openjaw nabídka bez returnDate"

# 6. Calendar data for routes in latest.json
echo ""
echo "[6/7] Calendar data coverage..."
ROUTES=$(jq -r '.[].routeKey' public/data/latest.json | sort -u)
MISSING_CALENDARS=0
for route in $ROUTES; do
  if [ ! -f "public/data/calendar/$route.json" ]; then
    echo "  ⚠ No calendar data for: $route"
    MISSING_CALENDARS=$((MISSING_CALENDARS + 1))
  fi
done
if [ $MISSING_CALENDARS -gt 0 ]; then
  echo "  (Note: $MISSING_CALENDARS routes missing calendar — okay if data not ready)"
fi
echo "✓ Calendar check complete"

# 6b. Datové podadresáře, které exporter zapisuje, MUSÍ být všude propsané:
#     stagované v scan.yml (jinak CI nezacommituje) a kopírované do web/public
#     v obou deploy cestách (deploy.yml i deploy.sh, jinak se nenasadí na Pages).
#     Regrese: exporter psal data/alternatives/, ale scan.yml je nestagoval a
#     deploy je nekopíroval → dlouhodobá řada „dražší varianty" se každý běh
#     ztratila. Tato kontrola hlídá, aby žádný nový podadresář nezůstal odpojený.
echo ""
echo "[6b] Data subdir wiring (scan + deploy)..."
DATA_SUBDIRS=(history calendar alternatives)
WIRING_FAILED=0
for sub in "${DATA_SUBDIRS[@]}"; do
  for target in \
    "$REPO_ROOT/.github/workflows/scan.yml:git add" \
    "$REPO_ROOT/.github/workflows/deploy.yml:deploy.yml sync" \
    "$REPO_ROOT/scripts/deploy.sh:deploy.sh sync"; do
    path="${target%:*}"
    label="${target#*:}"
    if ! grep -q "data/$sub" "$path"; then
      echo "  ❌ data/$sub není propsané v $label ($path)"
      WIRING_FAILED=1
    fi
  done
done
if [ $WIRING_FAILED -eq 1 ]; then exit 1; fi
echo "  ✓ history, calendar i alternatives jsou stagované i deployované"

# 7. Optional: Test deployed site (requires network + curl)
echo ""
echo "[7/7] GitHub Pages deployment..."
if [ "${1:-}" = "--full" ]; then
  echo "  Checking https://medniledved.github.io/flight-watcher/..."
  if curl -sf https://medniledved.github.io/flight-watcher/ > /dev/null; then
    echo "  ✓ Site is accessible"
    # Quick check: index.html loads and contains expected strings
    if curl -s https://medniledved.github.io/flight-watcher/ | grep -q "Japan Flight Tracker"; then
      echo "  ✓ Site loads and renders"
    else
      echo "  ⚠ Site loads but content seems wrong"
    fi
  else
    echo "  ❌ Site not accessible (network error or Pages not configured)"
    exit 1
  fi
else
  echo "  Skipped (use --full to test deployed site)"
fi

echo ""
echo "=========================================="
echo "✓ ALL CHECKS PASSED — Ready to deploy"
echo "=========================================="
